---
all:
  children:
    dns:
      hosts:
        dns01:
          ansible_host: "{{ hostname }}.{{ domain }}"
        dns02:
          ansible_host: "{{ hostname }}.{{ domain }}"
        dns03:
          ansible_host: "{{ hostname }}.{{ domain }}"
        dns04:
          ansible_host: "{{ hostname }}.{{ domain }}"
    lab:
      hosts:
        lab01:
          ansible_host: 192.168.114.138
    shell:
      hosts:
        sprocket:
          ansible_host: 127.0.0.1
        cerebro:
          ansible_host: 192.168.100.66
...