---
  all:
    vars:
    children:
      dns:
        hosts:
          dns01:
            ansible_host: "{{ hostname }}.{{ domain }}"
          dns02:
            ansible_host: "{{ hostname }}.{{ domain }}"
          dns03:
            ansible_host: "{{ hostname }}.{{ domain }}"
          dns04:
            ansible_host: "{{ hostname }}.{{ domain }}"
      lab:
        hosts:
          centos-lab01:
            ansible_host: "{{ hostname }}.{{ domain }}"
      shell:
        hosts:
          sprocket:
            ansible_host: 127.0.0.1
          cerebro:
            ansible_host: "{{ hostname }}.{{ domain }}"
...