---
- name: Show VRF Facts
  hosts: nxos
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    nxos_provider:
      username: "{{ ansible_username }}"
      password: "{{ ansible_password }}"
      transport: nxapi
      host: "{{inventory_hostname}}"
  vars_files: ~/.ansible/vault
  tasks:
    - name: Gather VRF Information
      cisco.nxos.nxapi:
        commands: show vrf
      register: nxos_facts

    - name: Display VRF Information
      ansible.builtin.debug:
        msg: "{{ nxos_facts.stdout }}"
...
