---
- name: Show VRF Facts
  hosts: nxos
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  vars_files: ~/.ansible/vault
  tasks:
    - name: Gather VRF Information
      cisco.nxos.nxos_command:
        commands: show vrf
      register: nxos_facts

    - name: Display VRF Information
      ansible.builtin.debug:
        msg: "{{ nxos_facts.stdout }}"
...
