---

- name: Ansible User Creation
  hosts: all
  become: true
  become_user: corpaldorf
  vars_files: ~/.ansible/vault
  tasks:
    - name: Create ansible account 
      user:
        name: ansible
        password: "{{ vault_ansible_password }}"

    - name: Add ansible user to sudoers 
      shell: usermod -aG sudo ansible
      args:
        executable: /bin/bash

    - name: Create .ssh Folder for Ansible User 
      file:
        path: ~/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: "0700" 

    - name: Upload Ansible User's SSH key
      copy:
        src: ../files/id_ed25519.pub
        dest: ~/.ssh/id_ed25519.pub
        owner: ansible
        group: ansible
        mode: "0700" 

    - name: Upload authorized_keys file
      copy:
        src: ../files/authorized_keys
        dest: ~/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: "0700" 
