---
- name: Ansible User Creation
  hosts: all
  become: true
  vars_files: ~/ansible/vault.yaml
  tasks:
    - name: Create ansible account
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        home: /home/ansible

    - name: Create password for Ansible User
      ansible.builtin.user:
        name: ansible
        # password: "{{ vault_ansible_hashed_password }}"
        password: '$6$GcCBpoRkj0K/KF2g$NsfCNVP6GPQa9XNTwJIjYPuOI3kSrRkMh0tKpi/KBO0nIXh0KfRINfJH8uyMFGAShT.Trg4OtpVPuhDT15WE5/'

    - name: Add ansible user to sudoers
      community.general.sudoers:
        name: add-ansible-to-sudoers
        state: present
        user: ansible
        commands:
          - ALL

    - name: Create .ssh Folder for Ansible User
      ansible.builtin.file:
        path: /home/ansible/.ssh/
        state: directory
        owner: ansible
        group: ansible
        mode: "0700"

    - name: Upload Ansible User's SSH key
      ansible.builtin.copy:
        src: files/id_ed25519.pub
        dest: /home/ansible/.ssh/id_ed25519.pub
        owner: ansible
        group: ansible
        mode: "0700"

    - name: Upload authorized_keys file
      ansible.builtin.copy:
        src: files/authorized_keys
        dest: /home/ansible/.ssh/authorized_keys
        owner: ansible
        group: ansible
        mode: "0700"
...
