---
- name: Secure and Hardening of SSHD
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  vars_files: ~/ansible/vault.yml
  tasks:
    - name: Configure sshd
      ansible.builtin.include_role:
        name: willshersystems.sshd
      vars:
        sshd_config_namespace: accept-env
        sshd_manage_firewall: true
        sshd_manage_selinux: true
        sshd:
          Port: 1989
          PermitRootLogin: false
          PasswordAuthentication: false
          PubkeyAuthentication: true
          MaxSessions: 5
          MaxAuthTries: 2
          LoginGraceTime: 30
          MaxStartUps: 5:30:10
          AllowUsers:
            - jimmychanga
            - corpaldorf
            - ansible
...
